# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: buf.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tbuf.proto\"\x8f\x01\n\x07Request\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nbench_type\x18\x02 \x01(\t\x12\x0e\n\x06metric\x18\x03 \x01(\t\x12\x10\n\x08\x62\x61tch_id\x18\x05 \x01(\x05\x12\x12\n\nbatch_unit\x18\x04 \x01(\x05\x12\x12\n\nbatch_size\x18\x06 \x01(\x05\x12\x1a\n\x12\x61nalysis_parameter\x18\x07 \x01(\t\"X\n\x08Response\x12\n\n\x02id\x18\x01 \x01(\t\x12\x15\n\rlast_batch_id\x18\x02 \x01(\x05\x12\x17\n\x07\x62\x61tches\x18\x03 \x03(\x0b\x32\x06.Batch\x12\x10\n\x08\x61nalysis\x18\x04 \x01(\x01\"\x18\n\x05\x42\x61tch\x12\x0f\n\x07samples\x18\x01 \x03(\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'buf_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=14
  _REQUEST._serialized_end=157
  _RESPONSE._serialized_start=159
  _RESPONSE._serialized_end=247
  _BATCH._serialized_start=249
  _BATCH._serialized_end=273
# @@protoc_insertion_point(module_scope)
